=begin
#Pushy

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'pushy/api_client'
require 'pushy/api_error'
require 'pushy/version'
require 'pushy/configuration'

# Models
require 'pushy/models/api_error'
require 'pushy/models/notification'
require 'pushy/models/push_notification'
require 'pushy/models/push_response'

# APIs
require 'pushy/api/notifications_api'

module Pushy
  class << self
    # Customize default settings for the SDK using block.
    #   Pushy.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
