=begin
#Pushy

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'cgi'

module Pushy
  class NotificationsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # @param push_notification [PushNotification] 
    # @param [Hash] opts the optional parameters
    # @return [PushResponse]
    def push_post(push_notification, opts = {})
      data, _status_code, _headers = push_post_with_http_info(push_notification, opts)
      data
    end

    # @param push_notification [PushNotification] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(PushResponse, Integer, Hash)>] PushResponse data, response status code and response headers
    def push_post_with_http_info(push_notification, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NotificationsApi.push_post ...'
      end
      # verify the required parameter 'push_notification' is set
      if @api_client.config.client_side_validation && push_notification.nil?
        fail ArgumentError, "Missing the required parameter 'push_notification' when calling NotificationsApi.push_post"
      end
      # resource path
      local_var_path = '/push'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] || @api_client.object_to_http_body(push_notification) 

      # return_type
      return_type = opts[:return_type] || 'PushResponse' 

      # auth_names
      auth_names = opts[:auth_names] || ['ApiKeyAuth']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NotificationsApi#push_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
